# settings algo
algo_number = 2
algo_time = 15
# settings tech
tech_number = 10
tech_time = 1
# settings interview
interview_algo_number = 2
interview_algo_time = 15
interview_tech_number = 5
interview_tech_time = 1